; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2
; estimated printing time (normal mode) = 1h 20m 5s
; total filament used [g] = 12.5
; total filament used [m] = 4.2
; total filament used [mm3] = 10080.65
; HEADER_BLOCK_END
G28
G1 X10 Y10 F3000
